package model;
// Generated 6 nov. 2024, 13:56:39 by Hibernate Tools 5.5.9.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cours generated by hbm2java
 */
public class Cours implements java.io.Serializable {

	private Integer idCours;
	private String nom;
	private String description;
	private float coef;
	private Set resultats = new HashSet(0);
	private Set inscriptionEnseignants = new HashSet(0);
	private Set inscriptions = new HashSet(0);

	public Cours() {
	}

	public Cours(String nom, String description, float coef) {
		this.nom = nom;
		this.description = description;
		this.coef = coef;
	}

	public Cours(String nom, String description, float coef, Set resultats, Set inscriptionEnseignants,
			Set inscriptions) {
		this.nom = nom;
		this.description = description;
		this.coef = coef;
		this.resultats = resultats;
		this.inscriptionEnseignants = inscriptionEnseignants;
		this.inscriptions = inscriptions;
	}

	public Integer getIdCours() {
		return this.idCours;
	}

	public void setIdCours(Integer idCours) {
		this.idCours = idCours;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public float getCoef() {
		return this.coef;
	}

	public void setCoef(float coef) {
		this.coef = coef;
	}

	public Set getResultats() {
		return this.resultats;
	}

	public void setResultats(Set resultats) {
		this.resultats = resultats;
	}

	public Set getInscriptionEnseignants() {
		return this.inscriptionEnseignants;
	}

	public void setInscriptionEnseignants(Set inscriptionEnseignants) {
		this.inscriptionEnseignants = inscriptionEnseignants;
	}

	public Set getInscriptions() {
		return this.inscriptions;
	}

	public void setInscriptions(Set inscriptions) {
		this.inscriptions = inscriptions;
	}

}
