package model;
// Generated 6 nov. 2024, 13:56:39 by Hibernate Tools 5.5.9.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Enseignant generated by hbm2java
 */
public class Enseignant implements java.io.Serializable {

	private Integer idEns;
	private Utilisateur utilisateur;
	private String nom;
	private String prenom;
	private String contact;
	private Set inscriptionEnseignants = new HashSet(0);

	public Enseignant() {
	}

	public Enseignant(Utilisateur utilisateur, String nom, String prenom, String contact) {
		this.utilisateur = utilisateur;
		this.nom = nom;
		this.prenom = prenom;
		this.contact = contact;
	}

	public Enseignant(Utilisateur utilisateur, String nom, String prenom, String contact, Set inscriptionEnseignants) {
		this.utilisateur = utilisateur;
		this.nom = nom;
		this.prenom = prenom;
		this.contact = contact;
		this.inscriptionEnseignants = inscriptionEnseignants;
	}

	public Integer getIdEns() {
		return this.idEns;
	}

	public void setIdEns(Integer idEns) {
		this.idEns = idEns;
	}

	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public Set getInscriptionEnseignants() {
		return this.inscriptionEnseignants;
	}

	public void setInscriptionEnseignants(Set inscriptionEnseignants) {
		this.inscriptionEnseignants = inscriptionEnseignants;
	}

}
