package model;
// Generated 6 nov. 2024, 13:56:39 by Hibernate Tools 5.5.9.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;

/**
 * Etudiant generated by hbm2java
 */
public class Etudiant implements java.io.Serializable {

	private Integer idEtu;
	
	
	@OneToOne
	@JoinColumn(name = "id_etu", referencedColumnName = "id_utilisateur", insertable = false, updatable = false)
	private Utilisateur utilisateur;
	private String nom;
	private String prenom;
	private Date dateNaissance;
	private String contact;
	private float moyenne;
	private Set inscriptions = new HashSet(0);
	private Set resultats = new HashSet(0);

	public Etudiant() {
	}

	public Etudiant(Utilisateur utilisateur, String nom, String prenom, Date dateNaissance, String contact,
			float moyenne) {
		this.utilisateur = utilisateur;
		this.nom = nom;
		this.prenom = prenom;
		this.dateNaissance = dateNaissance;
		this.contact = contact;
		this.moyenne = moyenne;
	}

	public Etudiant(Utilisateur utilisateur, String nom, String prenom, Date dateNaissance, String contact,
			float moyenne, Set inscriptions, Set resultats) {
		this.utilisateur = utilisateur;
		this.nom = nom;
		this.prenom = prenom;
		this.dateNaissance = dateNaissance;
		this.contact = contact;
		this.moyenne = moyenne;
		this.inscriptions = inscriptions;
		this.resultats = resultats;
	}

	public Integer getIdEtu() {
		return this.idEtu;
	}

	public void setIdEtu(Integer idEtu) {
		this.idEtu = idEtu;
	}

	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public Date getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public float getMoyenne() {
		return this.moyenne;
	}

	public void setMoyenne(float moyenne) {
		this.moyenne = moyenne;
	}

	public Set getInscriptions() {
		return this.inscriptions;
	}

	public void setInscriptions(Set inscriptions) {
		this.inscriptions = inscriptions;
	}

	public Set getResultats() {
		return this.resultats;
	}

	public void setResultats(Set resultats) {
		this.resultats = resultats;
	}

	
	
}
