package model;
// Generated 6 nov. 2024, 13:56:39 by Hibernate Tools 5.5.9.Final

import java.util.Date;

/**
 * Inscription generated by hbm2java
 */
public class Inscription implements java.io.Serializable {

	private Integer idIns;
	private Cours cours;
	private Etudiant etudiant;
	private Date dateInscription;

	public Inscription() {
	}

	public Inscription(Cours cours, Etudiant etudiant, Date dateInscription) {
		this.cours = cours;
		this.etudiant = etudiant;
		this.dateInscription = dateInscription;
	}

	public Integer getIdIns() {
		return this.idIns;
	}

	public void setIdIns(Integer idIns) {
		this.idIns = idIns;
	}

	public Cours getCours() {
		return this.cours;
	}

	public void setCours(Cours cours) {
		this.cours = cours;
	}

	public Etudiant getEtudiant() {
		return this.etudiant;
	}

	public void setEtudiant(Etudiant etudiant) {
		this.etudiant = etudiant;
	}

	public Date getDateInscription() {
		return this.dateInscription;
	}

	public void setDateInscription(Date dateInscription) {
		this.dateInscription = dateInscription;
	}

}
