package model;
// Generated 6 nov. 2024, 13:56:39 by Hibernate Tools 5.5.9.Final

/**
 * Resultat generated by hbm2java
 */
public class Resultat implements java.io.Serializable {

	private Integer idRes;
	private Cours cours;
	private Etudiant etudiant;
	private float note;

	public Resultat() {
	}

	public Resultat(Cours cours, Etudiant etudiant, float note) {
		this.cours = cours;
		this.etudiant = etudiant;
		this.note = note;
	}

	public Integer getIdRes() {
		return this.idRes;
	}

	public void setIdRes(Integer idRes) {
		this.idRes = idRes;
	}

	public Cours getCours() {
		return this.cours;
	}

	public void setCours(Cours cours) {
		this.cours = cours;
	}

	public Etudiant getEtudiant() {
		return this.etudiant;
	}

	public void setEtudiant(Etudiant etudiant) {
		this.etudiant = etudiant;
	}

	public float getNote() {
		return this.note;
	}

	public void setNote(float note) {
		this.note = note;
	}

}
