package model;
// Generated 6 nov. 2024, 13:56:39 by Hibernate Tools 5.5.9.Final

/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur implements java.io.Serializable {

	private Integer idUser;
	private String username;
	private String password;
	private int role;
	private int validation;
	private Admin admin;
	private Etudiant etudiant;
	private Enseignant enseignant;

	public Utilisateur() {
	}

	public Utilisateur(String username, String password, int role, int validation) {
		this.username = username;
		this.password = password;
		this.role = role;
		this.validation = validation;
	}

	public Utilisateur(String username, String password, int role, int validation, Admin admin, Etudiant etudiant,
			Enseignant enseignant) {
		this.username = username;
		this.password = password;
		this.role = role;
		this.validation = validation;
		this.admin = admin;
		this.etudiant = etudiant;
		this.enseignant = enseignant;
	}

	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public int getRole() {
		return this.role;
	}

	public void setRole(int role) {
		this.role = role;
	}

	public int getValidation() {
		return this.validation;
	}

	public void setValidation(int validation) {
		this.validation = validation;
	}

	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	public Etudiant getEtudiant() {
		return this.etudiant;
	}

	public void setEtudiant(Etudiant etudiant) {
		this.etudiant = etudiant;
	}

	public Enseignant getEnseignant() {
		return this.enseignant;
	}

	public void setEnseignant(Enseignant enseignant) {
		this.enseignant = enseignant;
	}
	
	public String toString() {
		return this.username;
	}

}
